### ISSUE TITLE
Improve the UI of the webpage 

### ISSUE THREAD

**Issue by programmerraja** [programmerraja/Weather-App#1]
Improve the Ui of the webpage

There is no restrictions you can improve the UI as much as you like but don't use bootstrap

HAPPY LEARNING

**Comment by vapx** [comment]
Would you mind if you assign it to me?

**Comment by Ramlanisagar** [comment]
@programmerraja can you please review my PR and a label of hacktober-accpeted if my PR is according to your guidelines.
